spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    username: changan
    password: 102410
    url: jdbc:mariadb://127.0.0.1:3306
#    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: star_bigdata
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
  #  主键自增
#  global-config:
#    db-config:
#      id-type: auto



server:
  port: 8000


  